config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :clients, only: [:index, :new, :create]
  resources :projects, only: [:create]
  resource :report, only: [:new] do
    post :employee, on: :member
    post :client, on: :member
    post :project, on: :member
  end

  resource :timesheet, only: [:new] do
    post :add_time, on: :member
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :project
  belongs_to :employee

  validates :project, presence: true
  validates :employee, presence: true
  validates :hours, presence: true
  validates :date, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :projects, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :activities, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  has_many :activities, dependent: :destroy

  validates :name, presence: true
  validates :client, presence: true
end

app/models/report.rb
class Report
  include ActiveModel::Model

  attr_accessor :employee, :client, :project, :date_from, :date_to

  def client_report
    projects = Project.where(client: client)
    projects.map(&:activities).flatten
  end

  def project_report
    Activity.where(project: project)
  end

  def date_range
    (Date.parse(date_from)..Date.parse(date_to)).to_a
  end

  def filled_in?(date)
    activity_dates.include?(date)
  end

  private

  def activity_dates
    @_employee_dates ||= Activity.where(employee: employee, date: date_from..date_to).pluck(:date)
  end
end

app/models/timesheet.rb
class Timesheet
  include ActiveModel::Model

  attr_accessor :project_name, :hours, :employee, :date, :new_project_name, :client_name, :new_client_name

  def add_time
    employee.activities.create!(activity_params)
  end

  private

  def activity_params
    {
      project: project,
      hours: hours,
      date: date
    }
  end

  def project
    if project_name.blank?
      Project.create!(name: new_project_name, client: client)
    else
      Project.find_by(name: project_name)
    end
  end

  def client
    if client_name.blank?
      Client.create!(name: new_client_name)
    else
      Client.find_by(name: client_name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end
  def new
    @client = Client.new
  end

  def create
    client = Client.new(client_params)
    if client.save
      flash[:notice] = "#{client.name} created"
      redirect_to clients_path
    else
      flash[:error] = "#{params.fetch(:name)} could not be created"
      redirect_to new_client_path
    end
  end

  private

  def client_params
    params.require(:client).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
    @report = Report.new
  end

  def employee
    @report = Report.new(report_params)
  end

  def client
    report = Report.new(report_params)
    @activities = report.client_report
  end

  def project
    report = Report.new(report_params)
    @activities = report.project_report
  end

  private

  def report_params
    params.require(:report).permit(:employee, :client, :project, :date_from, :date_to)
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :authenticate_employee!

  def new
    @timesheet = Timesheet.new
  end

  def add_time
    timesheet = Timesheet.new(timesheet_params)
    timesheet.add_time

    redirect_to new_timesheet_path
  end

  private

  def timesheet_params
    params.require(:timesheet).permit(:project_name, :hours, :date, :new_project_name, :client_name, :new_client_name).merge(employee: current_employee)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/clients/index.html.haml
%h1 Clients overview

%ul
  - @clients.each do |client|
    %li= client.name

= link_to 'Create new client', new_client_path

app/views/clients/new.html.haml
%h1 Create new client

= form_for @client do |f|
  = f.text_field :name
  = f.submit 'Submit'
= link_to 'Cancel', clients_path

app/views/home/index.html.haml
%h1
  Time tracker

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TimeTracker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %ul
      %li= link_to 'Clients', clients_path
      %li= link_to 'Add time', new_timesheet_path
      %li= link_to 'Report', new_report_path
      - if employee_signed_in?
        %li= link_to 'Log out', destroy_employee_session_path, method: :delete
      - else
        %li= link_to 'Log in', new_employee_session_path
        %li= link_to 'Sign up', new_employee_registration_path
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/reports/_missing.html.haml
%h1 Missing dates
%table
  %thead
    %tr 
      %th Date
      %th Filled in?
  - @report.date_range.each do |date|
    %tr
      %td= date
      %td= @report.filled_in?(date)

app/views/reports/_report.html.haml
- if @activities
  %h1 Activities
  %table
    %thead
      %tr 
        %th Date
        %th Client
        %th Project
        %th Employee
        %th Hours
    - @activities.each do |activity|
      %tr
        %td= activity.date
        %td= activity.project.client.name
        %td= activity.project.name
        %td= activity.employee.email
        %td= activity.hours

app/views/reports/client.js.haml
$('#report_container').html("#{j render(partial: 'report')}");

app/views/reports/employee.js.haml
$('#report_container').html("#{j render(partial: 'missing')}");

app/views/reports/new.html.haml
= form_for @report, url: employee_report_path, html: { method: :post, remote: true } do |f|
  = f.label :date_from
  = f.date_field :date_from, value: Time.now.strftime('%Y-%m-%d')

  = f.label :date_to
  = f.date_field :date_to, value: Time.now.strftime('%Y-%m-%d')
  
  = f.label :employee
  = f.collection_select(:employee, Employee.all, :id, :email, { include_blank: 'Select the employee', required: true })
  = f.submit 'Submit'

%p

= form_for @report, url: client_report_path, html: { method: :post, remote: true } do |f|
  = f.label :client
  = f.collection_select(:client, Client.all, :id, :name, { include_blank: 'Select the client', required: true })
  = f.submit 'Submit'

%p

= form_for @report, url: project_report_path, html: { method: :post, remote: true } do |f|
  = f.label :project
  = f.collection_select(:project, Project.all, :id, :name, { include_blank: 'Select the project', required: true })
  = f.submit 'Submit'

%p

#report_container
  No reports selected

app/views/reports/project.js.haml
$('#report_container').html("#{j render(partial: 'report')}");

app/views/timesheets/new.html.haml
%h1 Add your time

= form_for @timesheet, url: {action: 'add_time', controller: 'timesheets'} do |f|
  = f.label :date
  = f.date_field :date, value: Time.now.strftime('%Y-%m-%d')

  = f.label :client
  = f.collection_select(:client_name, Client.all, :name, :name, { include_blank: 'Select the client', required: true })

  = f.label :add_new_client
  = f.text_field :new_client_name

  = f.label :project
  = f.grouped_collection_select(:project_name, Client.all, :projects, :name, :name, :name, { include_blank: 'Select your project'})

  = f.label :add_new_project
  = f.text_field :new_project_name

  = f.label :hours
  = f.number_field :hours, step: 0.5

  = f.submit 'Submit'